--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 4/12/2023 5:23:03 PM
-- Server version: 10.4.27
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS autokolcsonzo;

CREATE DATABASE IF NOT EXISTS autokolcsonzo
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE autokolcsonzo;

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id INT(11) NOT NULL,
  firstName VARCHAR(255) DEFAULT NULL,
  lastName VARCHAR(255) DEFAULT NULL,
  gender VARCHAR(255) DEFAULT NULL,
  userName VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  number INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `userName` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX userName(userName);

--
-- Create index `email` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX email(email);

--
-- Create table `loans`
--
CREATE TABLE IF NOT EXISTS loans (
  id INT(11) NOT NULL,
  loanId INT(11) DEFAULT NULL,
  carId INT(11) DEFAULT NULL,
  loanStart DATE NOT NULL,
  numberOfDays INT(11) DEFAULT NULL,
  dailyRate DECIMAL(10, 0) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `loaners`
--
CREATE TABLE IF NOT EXISTS loaners (
  id INT(11) NOT NULL,
  name VARCHAR(100) NOT NULL,
  licenseNum VARCHAR(15) NOT NULL,
  phoneNum VARCHAR(15) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `cars`
--
CREATE TABLE IF NOT EXISTS cars (
  id INT(11) NOT NULL,
  license VARCHAR(6) NOT NULL,
  type VARCHAR(100) NOT NULL,
  year INT(11) DEFAULT NULL,
  color VARCHAR(30) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `license` on table `cars`
--
ALTER TABLE cars 
  ADD UNIQUE INDEX license(license);

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'Szilágyi', 'Brendon', 'male', 'brecsi', 'brecsi@gmail.com', '123', 1),
(2, 'Bajor', 'Vivien', 'female', 'laracroft41', 'laracroft41@gmail.com', '123', 1),
(3, 'Boros', 'Tamás', 'male', 'tomje', 'tomjeastar@gmail.com', '123', 0),
(4, 'Nagy', 'Gergő', 'male', 'slip', 'slip537@gmail.com', '123', 0);

-- 
-- Dumping data for table loans
--
INSERT INTO loans VALUES
(1, 1, 3, '2023-01-05', 21, 25000),
(2, 4, 2, '2023-02-10', NULL, 13000),
(3, 8, 1, '2022-12-22', NULL, 17500),
(4, 5, 5, '2022-12-10', 40, 11500);

-- 
-- Dumping data for table loaners
--
INSERT INTO loaners VALUES
(1, 'Nagy Béla', '536012056314012', '06705519280'),
(2, 'Kiss János', '509234527416861', '06306571231'),
(3, 'Fekete Pál', '185512685049050', '06204458163'),
(4, 'Nagy Károly', '684811260235354', '06309976544'),
(5, 'Beton Károly', '116098956271829', '06703217455'),
(6, 'Pogány Krisztián', '190532681943455', '06208893327'),
(7, 'Kiss Bertalan', '890426785007182', '06708839214'),
(8, 'Nádas Péter', '182666784821177', '06306659321'),
(9, 'Rigó Zoltán', '099796949378155', '06205764585'),
(10, 'Nagy Péter', '587259761216499', '06304518753');

-- 
-- Dumping data for table cars
--
INSERT INTO cars VALUES
(1, 'KFH271', 'Volkswagen', 2003, 'Black'),
(2, 'OEJ813', 'Mercedes', 2018, 'Grey'),
(3, 'AXE809', 'BMW', 2022, 'Black'),
(4, 'KEG600', 'Ford', 2001, 'Blue'),
(5, 'BFG915', 'Suzuki', 1999, 'Red'),
(6, 'LKE642', 'Peugeot', 2005, 'Blue'),
(7, 'KYR241', 'Cadillac', 2018, 'White'),
(8, 'HJY381', 'Daewoo', 1997, 'Green'),
(9, 'ABU885', 'Koenigsegg', 2020, 'Yellow'),
(10, 'SKY845', 'Nissan', 2004, 'Blue');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;